<?php

namespace Raumverwaltung;

class LehrerBueros extends Buero
{
private string $LehrerName;

public function KlimaanlageAn(): void
{
    parent::KlimaanlageAn(); // TODO: Change the autogenerated stub
}
}