version: '3.5'

services:
  KochRezept_db:
    image: mysql:5.7
    container_name: KochRezept_db
    command: --init-file /initSql/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./../data_db:/var/lib/mysql
      - ./sql/init.sql:/initSql/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: asdqwe123
      MYSQL_DATABASE: KochRezept
      MYSQL_USER: asdqwe123
      MYSQL_PASSWORD: asdqwe123
    networks:
      - KochRezept_NET

  KochRezept_php:
    build:
      context: ./enviroment/development/php
    image: kr_php
    container_name: KochRezept_php
    ports:
      - 9000:9000
    volumes:
      - ./../:/srv/
      - ./enviroment/development/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - KochRezept_NET

  KochRezept_nginx:
    image: nginx:1.16.1
    container_name: KochRezept_nginx
    ports:
      - 80:80
    volumes:
      - ./../:/srv/
      - ./enviroment/development/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - KochRezept_NET

volumes:
  data_db:

networks:
  KochRezept_NET:
    name: KochRezept_NET
